#!/bin/bash
# read mqtt messages in a loop and send them to indiserver
# 18.11.2021 antrares

mqtt_host="*****"
mqtt_port="*****"
mqtt_id="*****"
mqtt_topic="*****"

while read line; do

prop=${line%%=*}
value=${line##*=}

case $prop in
	"rt_connection")
		if [ $value == "1" ]; then
		indi_setprop "Weather Watcher.CONNECTION.CONNECT=On" 2>/dev/null
		sleep 1
		indi_setprop "GPSD.CONNECTION.CONNECT=On" 2>/dev/null
		sleep 5
		indi_setprop "Pi Radiotelescope.CONNECTION.CONNECT=On" 2>/dev/null
		fi
		if [ $value == "0" ]; then
		indi_setprop "Pi Radiotelescope.CONNECTION.DISCONNECT=On" 2>/dev/null
		sleep 1
		indi_setprop "Weather Watcher.CONNECTION.DISCONNECT=On" 2>/dev/null
		sleep 1
		indi_setprop "GPSD.CONNECTION.DISCONNECT=On" 2>/dev/null
		fi
	;;
	"rt_park")
		if [ $value == "1" ]; then
		indi_setprop "Pi Radiotelescope.TELESCOPE_PARK.PARK=On" 2>/dev/null
		fi
		if [ $value == "0" ]; then
		indi_setprop "Pi Radiotelescope.TELESCOPE_PARK.UNPARK=On" 2>/dev/null
		fi
	;;
	"rt_trackstate")
		if [ $value == "1" ]; then
		indi_setprop "Pi Radiotelescope.TELESCOPE_TRACK_STATE.TRACK_ON=On" 2>/dev/null
		fi
		if [ $value == "0" ]; then
		indi_setprop "Pi Radiotelescope.TELESCOPE_TRACK_STATE.TRACK_OFF=On" 2>/dev/null
		fi
	;;
	"gpio0")
		if [ $value == "1" ]; then
		indi_setprop "Pi Radiotelescope.GPIO_OUTPUTS.GPIO_OUT0=On" 2>/dev/null
		fi
		if [ $value == "0" ]; then
		indi_setprop "Pi Radiotelescope.GPIO_OUTPUTS.GPIO_OUT0=Off" 2>/dev/null
		fi
	;;
	"rt_abort")
		if [ $value == "1" ]; then
		indi_setprop "Pi Radiotelescope.TELESCOPE_ABORT_MOTION.ABORT=On" 2>/dev/null
		sleep 1
		indi_setprop "Pi Radiotelescope.TELESCOPE_PARK.UNPARK=On" 2>/dev/null
		sleep 1
		indi_setprop "Pi Radiotelescope.TELESCOPE_TRACK_STATE.TRACK_OFF=On" 2>/dev/null
		fi
	;;
	"weather_override")
		if [ $value == "1" ]; then
		indi_setprop "Weather Watcher.WEATHER_OVERRIDE.OVERRIDE=On" 2>/dev/null
		fi
		if [ $value == "0" ]; then
		indi_setprop "Weather Watcher.WEATHER_OVERRIDE.OVERRIDE=Off" 2>/dev/null
		fi
	;;
	"rt_slewrate")
		case $value in
			"1") cmd="Pi Radiotelescope.TELESCOPE_SLEW_RATE.1x=On" ;;
			"2") cmd="Pi Radiotelescope.TELESCOPE_SLEW_RATE.2x=On" ;;
			"3") cmd="Pi Radiotelescope.TELESCOPE_SLEW_RATE.3x=On" ;;
			"4") cmd="Pi Radiotelescope.TELESCOPE_SLEW_RATE.4x=On" ;;
			"5") cmd="Pi Radiotelescope.TELESCOPE_SLEW_RATE.5x=On" ;;
			*) ;;
		esac
		indi_setprop "$cmd" 2>/dev/null
	;;
	*)
	;;
esac

done < <(mosquitto_sub --quiet -h $mqtt_host  -p $mqtt_port  -i $mqtt_id  -t $mqtt_topic)
