#!/bin/bash
# read ratsche tasklist in a loop and send them to a MQTT broker
# 10.11.2021 antrares

# usage: ./rt_ratsche_to_mqtt <DELAY>
# with the optional argument DELAY: waiting time BEFORE each poll in s

DELAY=10.0

mqtt_host="*****"
mqtt_port="*****"
mqtt_id="*****"
mqtt_topic="*****"


while :
do

sleep $DELAY

ratsche_msg=$(ratsche -lr 2>/dev/null)

mosquitto_pub --quiet -h $mqtt_host  -p $mqtt_port  -i $mqtt_id  -t $mqtt_topic  -m "$ratsche_msg"

done
