#!/bin/bash
# show RT position and onboard adc values in a loop
# 11/04/2021 HGZ

# usage: ./rt_measurement.sh <N> <DELAY>
# with the optional two arguments
# N: number of measurements in a loop, zero for endless loop
N=0
# DELAY: waiting time BEFORE each measurement in s
DELAY=0.0

if [ $# -eq 1 ]; then
   N=$1
fi

if [ $# -eq 2 ]; then
   N=$1
   DELAY=$2
fi

indi_device="Pi Radiotelescope"
cmd_indi="indi_getprop -t 5 -1"
cmd_date="date '+%s.%N'"

prop_az="HORIZONTAL_EOD_COORD.AZ"
prop_alt="HORIZONTAL_EOD_COORD.ALT"
prop_ra="EQUATORIAL_EOD_COORD.RA"
prop_dec="EQUATORIAL_EOD_COORD.DEC"
prop_temp1="TEMPERATURE_MONITOR.TEMPERATURE1"
prop_temp2="TEMPERATURE_MONITOR.TEMPERATURE2"
prop_adc1="MEASUREMENTS.MEASUREMENT0"
prop_adc2="MEASUREMENTS.MEASUREMENT1"

# make number of measurements
count=0
while [[ $count -lt $N ]] || [[ $N == 0 ]]
do
  sleep $DELAY
  indi_props=$($cmd_indi "$indi_device.$prop_ra" "$indi_device.$prop_dec" \
  "$indi_device.$prop_az" "$indi_device.$prop_alt" \
  "$indi_device.$prop_adc1" "$indi_device.$prop_adc2" \
  "$indi_device.$prop_temp1" "$indi_device.$prop_temp2" \
  2>/dev/null)
  
  for i in $indi_props; do
    if echo $i | grep -qe $prop_ra
    then
      ra=$(echo $i | awk -F"=" '{ x=strtonum($(NF)); h=int(x); m=int((x-h)*60); s=int(((x-h)*60-m)*60) ; printf "%2d:%02d:%02d", h, m, s }')
    fi
    if echo $i | grep -qe $prop_dec
    then
      dec=$(echo $i | awk -F"=" '{ x=strtonum($(NF)); d=int(x); m=sqrt(int((x-d)*60)^2); s=int((sqrt((x-d)^2)*60-m)*60); printf "%+2d:%02d:%02d", d, m, s }')
    fi
    if echo $i | grep -qe $prop_az
    then
      az=$(echo $i | awk -F"=" '{ x=strtonum($(NF)); d=int(x); m=int((x-d)*60); s=int(((x-d)*60-m)*60); printf "%3d:%02d:%02d", d, m, s }')
    fi
    if echo $i | grep -qe $prop_alt
    then
      alt=$(echo $i | awk -F"=" '{ x=strtonum($(NF)); d=int(x); m=sqrt(int((x-d)*60)^2); s=int((sqrt((x-d)^2)*60-m)*60); printf "%+2d:%02d:%02d", d, m, s }')
    fi
    if echo $i | grep -qe $prop_temp1
    then
      temp1=$(echo $i | awk -F"=" '{ printf "%1.1f", strtonum($(NF)) }')
    fi
    if echo $i | grep -qe $prop_temp2
    then
      temp2=$(echo $i | awk -F"=" '{ printf "%1.1f", strtonum($(NF)) }')
    fi
    if echo $i | grep -qe $prop_adc1
    then
      adc1=$(echo $i | awk -F"=" '{ printf "%1.4f", strtonum($(NF)) }')
    fi
    if echo $i | grep -qe $prop_adc2
    then
      adc2=$(echo $i | awk -F"=" '{ printf "%1.4f", strtonum($(NF)) }')
    fi
  done
  echo $(eval $cmd_date) $az $alt $ra $dec $adc1 $adc2 $temp1 $temp2
  let count=$count+1
done
